version: '3.8'

services:
  git-client:
    image: alpine/git:latest
    container_name: brew-haven-git
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh:ro  # Mount SSH keys if using SSH
      - ~/.gitconfig:/root/.gitconfig:ro  # Mount git config
    environment:
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-Developer}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-developer@example.com}
      - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME:-Developer}
      - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL:-developer@example.com}
    command: sh
    stdin_open: true
    tty: true
    network_mode: host