version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
    environment:
      - S3_BUCKET_NAME=coffeeshop-bucket-local
      - DYNAMODB_TABLE_NAME=coffeeShopDB
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
    networks:
      - coffeeshop-network
    entrypoint: >
      /bin/bash -c "
        # Apply patches
        /app/docker/scripts/03-apply-patches.sh
        # Run the application
        uvicorn main:app --host 0.0.0.0 --port 8080 --reload
      "

  localstack:
    image: localstack/localstack:0.14.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./scripts:/docker-entrypoint-initaws.d
    networks:
      - coffeeshop-network

networks:
  coffeeshop-network:
    driver: bridge

volumes:
  localstack-data: 